### ISSUE TITLE
Oluşturulan test caseleri içerisinde expected status code / expected body bilgilerine göre assertion işlemini yapacak. 

### ISSUE THREAD

**Issue by zkylab** [zkylab/easyresttest#3]
Hamcrest (Rest Assured içerisinde mevcut) kullanılarak basit assertion kodları generate edilecek. Bu assertionlar direkt olarak tüm test faaliyetlerinde kullanılmasa bile kütüphaneyi kullanacak arkadaşların rahatlıkla editleme yapabileceği temel bir yapı oluşturmayı sağlayacaktır.

**Comment by MTalhaSongur** [comment]
Başlanmıştır.

**Comment by MTalhaSongur** [comment]
Tamamlandı.
